# Numpy

In [2]:
import numpy as np

In [3]:
arr = np.array([1,2,3,4,5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [4]:
arr = np.array((1,2,3,4,5))
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


### Dimensions in array

In [5]:
arr = np.array(20)
print(arr)
print(type(arr))
print(arr.ndim)

20
<class 'numpy.ndarray'>
0


### 1-D array

In [6]:
arr = np.array([1,2,3,4,5,6])
print(arr)
print(arr.ndim)

[1 2 3 4 5 6]
1


### 2-D array

In [7]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr)
print(arr.ndim)

[[1 2 3]
 [4 5 6]]
2


In [8]:
arr = np.array([[1.1,2.2,3.2],[4.4,5,6]])
print(arr)
print(arr.ndim)

[[1.1 2.2 3.2]
 [4.4 5.  6. ]]
2


### 3-D array
An array that has 2-D arrays (matrices) as its elements is called 3-D array.

In [9]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [10]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(arr)
print(type(arr))
print(arr.ndim)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
<class 'numpy.ndarray'>
3


In [11]:
a = np.array(42)
b = np.array([1,2,3,4,5])
c = np.array([[1,2,3], [4,5,6]])
d = np.array([[[1,2,3], [4,5,6]], [[1,2,3], [4,5,6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


### Higher Dimensional Array
An array can have any number of dimensions.

When the array is created, you can define the number of dimensions by using the ndim argument

### Create an array with 5 dimensions and verify that it has 5 dimensions:

In [12]:
arr = np.array([1,2,3,4], ndmin = 5)

print(arr)
print('number of dimensions:', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions: 5


### Numpy Array Indexing
Array indexing is same as accessing an array element.

You can access an array element by referring to its index number.

The indexes in numpy arrays start with 0.meaning that the first element has index 0.and the second index has index 1 etc.

### Get the first element from the following array:

In [13]:
arr = np.array([1, 2, 3, 4])
print(arr[0])

1


### get third and sixth and eighth elements from the following array and add them

In [14]:
m = np.array([41,87,34,56.8,39.23,90,15,10,19,56])
print("the second elememnt is", m[2])
print("the sixth element is", m[5])
print("the eighth element is", m[7])
print("sum of this elements are", m[2]+m[5]+m[7])

the second elememnt is 34.0
the sixth element is 90.0
the eighth element is 10.0
sum of this elements are 134.0


### Access 2-D Arrays
To access elements from 2-D arrays we can use comma seperated integers representing the dimension and the index of the element.

Think of 2-D arrays like a table with rows and columns, where the dimension represents the row and the index represents the column.

In [15]:
arr = np.array([[10,20,30,40,50], [60,70,80,90,100]])

print('2nd element on 1st row: ', arr[0,1])

2nd element on 1st row:  20


In [16]:
arr = np.array([[10,20,30,40,50], [60,70,80,90,100]])

print('4th element on 1st row: ', arr[0, 3])

4th element on 1st row:  40


In [17]:
arr = np.array([[10,20,30,40,50], [60,70,80,90,100]])

print('1st element on 2nd row: ', arr[1, 0])

1st element on 2nd row:  60


In [18]:
arr = np.array([[10,20,30,40,50], [60,70,80,90,100]])

print('last element on 2nd row: ', arr[1, 4])

last element on 2nd row:  100


### add the first element of row 1 and last element 

In [19]:
arr = np.array([[10,20,30,40,50], [60,70,80,90,100]])

print('First element of 1st row: ', arr[0, 0])
print('last element of 2nd row: ', arr[1, 4])
print("sum is", arr[0,0]+arr[1, 4]) 

First element of 1st row:  10
last element of 2nd row:  100
sum is 110


### Access 3-D Arrays
To access elements from 3-D arrays we can use comma seperated integers representing the dimensions and the index of the element.

In [20]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(arr[0, 1, 2])

6


In [21]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(arr[1, 1, 2])

12


In [22]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(arr[1, 0, 1])

8


### slicing of numpy arrays

In [23]:
arr = np.array([1,2,3,4,5,6,7])
print(arr[1:5])

[2 3 4 5]


In [24]:
arr = np.array([1,2,3,4,5,6,7])
print(arr[::2])

[1 3 5 7]


### slicing in 2-D array

In [25]:
a = np.array([[10,20,30,40,50],[60,70,80,90,100]])
print(a[1,1:4])

[70 80 90]


In [26]:
a = np.array([[10,20,30,40,50],[60,70,80,90,100]])
print(a[0,0:3])

[10 20 30]


### checking the data type of an array

In [27]:
np.array([1,2,3,4])
print(arr.dtype)

int32


In [28]:
arr = np.array(['animals', 'bat', 'cat'])
print(arr.dtype)

<U7


### creating a data with a defined data type

In [29]:
arr = np.array([1,2,3,4], dtype = 'S')
print(arr)
print()
print(arr.dtype)

[b'1' b'2' b'3' b'4']

|S1


### numpy array shape
the shape of an array is the number of elements in each dimension

### point the shape of a 2d array

In [30]:
arr = np.array([[1,2,3,4],[5,6,7,8]])
print(arr.shape)

(2, 4)


In [31]:
arr = np.array([[[1,2,3,4], [5,6,7,8], [10,20,30,40]]])
print(arr.shape)

(1, 3, 4)


### joining numpy arrays

In [32]:
arr1 = np.array([1,2,3])

arr2 = np.array([4,5,6])

arr = np.concatenate((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


### join 2 D arrays

In [33]:
arr1 = np.array([[1,2], [3,4]])

arr2 = np.array([[5,6], [7,8]])

arr = np.concatenate((arr1, arr2), axis = 1)

print(arr)

[[1 2 5 6]
 [3 4 7 8]]


In [34]:
arr1 = np.array([[1,2], [3,4]])

arr2 = np.array([[5,6], [7,8]])

arr = np.concatenate((arr1, arr2), axis=0)

print(arr)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


### splitting numpy arrays 

### splitting the array in 3 parts

In [35]:
arr = np.array([1,2,3,4,5,6])

newarr = np.array_split(arr,3)

print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


### splitting the array in 4 parts

In [36]:
arr = np.array([1,2,3,4,5,6])

newarr = np.array_split(arr,4)

print(newarr)

[array([1, 2]), array([3, 4]), array([5]), array([6])]


### ravel & flatten
converts multidimensional array into 1 d array

In [37]:
m = np.array([[[1,2,3], [4,5,6], [7,8,9]]])
print(m)
print("dimension is", m.ndim)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
dimension is 3


In [38]:
m = np.array([[[1,2,3], [4,5,6], [7,8,9]]])
print(m)
print("dimension is", m.ndim)
n = m.ravel() / m.flatten()
print(m)
print("now the new dimension is n.ndim")

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
dimension is 3
[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
now the new dimension is n.ndim


In [39]:
c = np.array([[[[1,2,3], [78,89,25], [45,26,84]]]])
print(c)
print("the dimension is", c.ndim)
d = c.ravel()
print(d)
print("niw the new dimension is", n.ndim)

[[[[ 1  2  3]
   [78 89 25]
   [45 26 84]]]]
the dimension is 4
[ 1  2  3 78 89 25 45 26 84]
niw the new dimension is 1


### unique function

In [40]:
k = np.array([12,1,4,6,7,9,3,4,5,22,33,7,6,1,2,12])
print(k)
x = np.unique(k)
print(x)

[12  1  4  6  7  9  3  4  5 22 33  7  6  1  2 12]
[ 1  2  3  4  5  6  7  9 12 22 33]


In [41]:
k = np.array([12,1,4,6,7,9,3,4,5,22,33,7,9,1,2,12])
print(k)
x = np.unique(k, return_index=True, return_counts=True)
print(x)

[12  1  4  6  7  9  3  4  5 22 33  7  9  1  2 12]
(array([ 1,  2,  3,  4,  5,  6,  7,  9, 12, 22, 33]), array([ 1, 14,  6,  2,  8,  3,  4,  5,  0,  9, 10], dtype=int64), array([2, 1, 1, 2, 1, 1, 2, 2, 2, 1, 1], dtype=int64))


### delete

In [42]:
a = np.array([12,13,14,15])
d = np.delete(a,[1])
print(d)

[12 14 15]


In [43]:
x = np.array([[2,7,9,6,8],[4,5,7,1,2],[50,0,65,6,7]])
print(x)

[[ 2  7  9  6  8]
 [ 4  5  7  1  2]
 [50  0 65  6  7]]


In [44]:
x = np.array([[2,7,9,6,8],[4,5,7,1,2],[50,0,65,6,7]])
print(x)
m = np.delete(x,1,axis=0)
print()
print(m)

[[ 2  7  9  6  8]
 [ 4  5  7  1  2]
 [50  0 65  6  7]]

[[ 2  7  9  6  8]
 [50  0 65  6  7]]
